server:
  port: 8070

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atm
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    liquibase :
      enabled : false
  messages:
    basename: messages


logging:
  file:
    path: ./
    name: logfile.log
